name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish-npm:
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install
      - name: Lint with ESLint
        run: npm run lint
      - name: Build Library
        run: npm run build
      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPMJS_TOKEN }}
